"""open_harvest: Commons Harvest where the ripeness stage an apple is eaten at sets, per hue, its points and how fast its cell regrows.

Vanilla harvest_open.py with (1) apples that carry a hue (one hue per patch; the patch letters of the map are slots and every meta-episode draws a
distinct hue for each slot, e.g. 3 of the 5 hues on the mini map) and a visible
ripeness stage that advances every `ripen_steps` steps and rots after the last stage, (2) the vanilla
neighbour-count regrowth probabilities multiplied by a hidden per-hue speed (fast / normal / slow) chosen by the ripeness stage
the last apple of the cell had when it was eaten or rotted (State.last_stage), (3) a hidden per-hue
order in which the three ripeness stages pay 1 / 0.5 / 0.25 points (the same three amounts for every hue; State.values is kept, all ones),
(5) meta-episodes of num_outer_steps trials that re-lay the orchard but keep the rules and the values. Generated by scripts/make_open_harvest.py.
"""
from enum import IntEnum
import math
from typing import Any, Optional, Tuple, Union, Dict
from functools import partial

import chex
import jax
import jax.numpy as jnp
import numpy as onp
from flax.struct import dataclass
import colorsys

from opensocialjax.environments.movement import resolve_movement, resolve_respawn
from opensocialjax.environments.multi_agent_env import MultiAgentEnv
from opensocialjax.environments import spaces


from opensocialjax.environments.discovery_rules import (
    MAX_RULES, RULE_ENCODING_LEN, NUM_HARVEST_HUES, NUM_RIPE_STAGES, REGROW_RATES, STAGE_PAY, PAY_ORDERS,
    decode_harvest_ruleset, sample_harvest_ruleset,
)
from opensocialjax.environments.rendering import (
    downsample,
    fill_coords,
    highlight_img,
    point_in_circle,
    point_in_line,
    point_in_rect,
    point_in_triangle,
    rotate_fn,
)

NUM_TYPES = 4  # empty (0), red (1), blue, red coin, blue coin, wall, interact
NUM_COIN_TYPES = 1
INTERACT_THRESHOLD = 0


@dataclass
class State:
    agent_locs: jnp.ndarray
    agent_invs: jnp.ndarray
    inner_t: int
    outer_t: int
    grid: jnp.ndarray
    apples: jnp.ndarray

    freeze: jnp.ndarray
    reborn_locs: jnp.ndarray
    age: jnp.ndarray            # (num_apple_cells,) steps this apple has hung; 0 when the cell is empty; -k when the cell's apple rotted and it regrows by itself in k steps
    rule_encoding: jnp.ndarray  # (MAX_RULES, RULE_ENCODING_LEN) uint8: REGROW_RATE / RIPE_PEAK rows
    values: jnp.ndarray         # (num_agents, num_hues) uint8: all ones since 2026-09-16 (no per-hue value; kept so fixed_values / oracles still work)
    cell_hues: jnp.ndarray      # (num_apple_cells,) int32: hue of each tree cell this meta-episode (drawn per patch slot at reset)
    last_stage: jnp.ndarray     # (num_apple_cells,) int8: ripeness stage the cell's last apple had when it was eaten or rotted (with the hue's hidden speed order it sets the regrowth speed)
    ripen_len: jnp.ndarray      # (num_apple_cells,) int16: steps per ripeness stage of the apple on this cell, drawn from ripen_range when it grew (2026-09-19)
    zap_cd: jnp.ndarray         # (num_agents,) int16: steps left before this agent may fire again (Melting Pot cooldownTime)
    zap_wait: jnp.ndarray       # (num_agents,) int16: steps left on the spawn cell after being zapped, unable to act (Melting Pot framesTillRespawn)

@chex.dataclass
class EnvParams:
    payoff_matrix: chex.ArrayDevice
    freeze_penalty: int

class Actions(IntEnum):
    turn_left = 0
    turn_right = 1
    left = 2
    right = 3
    up = 4
    down = 5
    stay = 6
    zap_forward = 7
    # zap_ahead = 8
    # zap_right = 6
    # zap_left = 7

class Items(IntEnum):
    empty = 0
    wall = 1
    interact = 2
    apple = 3               # legacy generic code, unused on the grid (kept so vanilla code paths stay valid)
    spawn_point = 4
    inside_spawn_point = 5
    # hue h, stage s -> APPLE_BASE + h * NUM_RIPE_STAGES + s
    apple_r0 = 6;  apple_r1 = 7;  apple_r2 = 8
    apple_y0 = 9;  apple_y1 = 10; apple_y2 = 11
    apple_g0 = 12; apple_g1 = 13; apple_g2 = 14
    apple_c0 = 15; apple_c1 = 16; apple_c2 = 17
    apple_m0 = 18; apple_m1 = 19; apple_m2 = 20


APPLE_BASE = int(Items.apple_r0)
NUM_APPLE_CODES = NUM_HARVEST_HUES * NUM_RIPE_STAGES      # 15
HUE_NAMES = ("red", "yellow", "green", "cyan", "purple")
STAGE_NAMES = ("green", "ripe", "over")
HUE_LETTERS = "RYGCM"                                     # map letters for single-hue patches
SLOT_LETTERS = HUE_LETTERS + "S"                          # patch slots a map can use: the five above plus a sixth, for maps with
                                                          # more patches than hues (their hues must then be drawn with replacement)
_MAP_HUE_CODE = 30                                        # 'R' -> 30 ... 'M' -> 34, 'S' -> 35 in the parsed ASCII map


def is_apple(code):
    return (code >= APPLE_BASE) & (code < APPLE_BASE + NUM_APPLE_CODES)


def apple_hue(code):
    return (code - APPLE_BASE) // NUM_RIPE_STAGES


def apple_stage(code):
    return (code - APPLE_BASE) % NUM_RIPE_STAGES

    
char_to_int = {
    'W': 1,
    ' ': 0,
    'A': 3,                       # generic apple cell: hue 0
    'P': 4,
    'Q': 5,
    **{c: _MAP_HUE_CODE + i for i, c in enumerate(SLOT_LETTERS)},  # single-hue patches (one slot per letter)
}

ROTATIONS = jnp.array(
    [
        [0, 0, 1],  # turn left
        [0, 0, -1],  # turn right
        [0, 0, 0],  # left
        [0, 0, 0],  # right
        [0, 0, 0],  # up
        [0, 0, 0],  # down
        [0, 0, 0],  # stay
        [0, 0, 0],  # zap
        # [0, 0, 0],
        # [0, 0, 0],
        # [0, 0, 0],
        # [0, 0, 0],
        # [0, 0, 0],
        # [0, 0, 1], # turn left
        # [0, 0, -1],  # turn right
        # [0, 0, 0]
    ],
    dtype=jnp.int8,
)

STEP = jnp.array(
    [
        [1, 0, 0],  # up
        [0, 1, 0],  # right
        [-1, 0, 0],  # down
        [0, -1, 0],  # left
    ],
    dtype=jnp.int8,
)

STEP_MOVE = jnp.array(
    [
        [0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],  
        [0, -1, 0],  
        [1, 0, 0],  
        [-1, 0, 0],  
        [0, 0, 0],
        [0, 0, 0],
    ],
    dtype=jnp.int8,
)



def ascii_map_to_matrix(map_ASCII, char_to_int):
    """
    Convert ASCII map to a JAX numpy matrix using the given character mapping.
    
    Args:
    map_ASCII (list): List of strings representing the ASCII map
    char_to_int (dict): Dictionary mapping characters to integer values
    
    Returns:
    jax.numpy.ndarray: 2D matrix representation of the ASCII map
    """
    # Determine matrix dimensions
    height = len(map_ASCII)
    width = max(len(row) for row in map_ASCII)
    
    # Create matrix filled with zeros
    matrix = jnp.zeros((height, width), dtype=jnp.int32)
    
    # Fill matrix with mapped values
    for i, row in enumerate(map_ASCII):
        for j, char in enumerate(row):
            matrix = matrix.at[i, j].set(char_to_int.get(char, 0))
    
    return matrix

# High-contrast, colourblind-friendly categorical palette: distinct on the
# sand background (the old HSV wheel produced low-contrast near-duplicate
# colours at 6+ agents).
AGENT_PALETTE = [
    (230, 25, 75),    # crimson
    (245, 130, 48),   # orange
    (255, 225, 25),   # yellow
    (240, 50, 230),   # magenta
    (70, 240, 240),   # cyan
    (145, 30, 180),   # purple
    (60, 180, 75),    # green
    (0, 130, 200),    # azure
    (250, 190, 212),  # pink
    (170, 110, 40),   # brown
]


def generate_agent_colors(num_agents):
    return [AGENT_PALETTE[i % len(AGENT_PALETTE)] for i in range(num_agents)]


# ---- tile style helpers (rendering only, cached per tile) -----------------
SAND_COLOUR = (201, 192, 165)
AGENT_OUTLINE_COLOUR = (25, 25, 28)



def paint_wall_tile(img):
    img[:, :] = (99, 102, 106)
    fill_coords(img, point_in_rect(0.0, 1.0, 0.0, 0.08), (122, 125, 130))
    fill_coords(img, point_in_rect(0.0, 0.08, 0.0, 1.0), (122, 125, 130))
    fill_coords(img, point_in_rect(0.0, 1.0, 0.92, 1.0), (80, 82, 86))


APPLE_HUE_RGB = ((214, 39, 40), (240, 200, 40), (60, 170, 70), (40, 180, 200), (170, 70, 200))


def paint_apple_tile(img, hue=0, stage=1):
    """Apple in the patch's hue; stage 0 small and green-tinted, 1 full colour, 2 dull/brown."""
    base = APPLE_HUE_RGB[hue]
    if stage == 0:
        col = tuple(int(0.55 * c + 0.45 * g) for c, g in zip(base, (120, 190, 90))); r = 0.24
    elif stage == 1:
        col = base; r = 0.30
    else:
        col = tuple(int(0.6 * c + 0.4 * b) for c, b in zip(base, (110, 80, 50))); r = 0.30
    rim = tuple(max(0, int(c * 0.6)) for c in col)
    fill_coords(img, point_in_circle(0.5, 0.54, r + 0.05), rim)
    fill_coords(img, point_in_circle(0.5, 0.54, r), col)
    fill_coords(img, point_in_rect(0.47, 0.53, 0.14, 0.30), (70, 140, 60))
    fill_coords(img, point_in_circle(0.41, 0.45, 0.06), (245, 235, 225))


def paint_beam_tile(img, glow, core, orient=None):
    """Beam segment: bright core + soft glow, oriented along the beam.

    orient: "h"/"v" for a segment whose neighbours continue horizontally/
    vertically, None for an isolated or corner cell (symmetric burst)."""
    if orient == "h":
        fill_coords(img, point_in_rect(0.0, 1.0, 0.18, 0.82), glow)
        fill_coords(img, point_in_rect(0.0, 1.0, 0.38, 0.62), core)
    elif orient == "v":
        fill_coords(img, point_in_rect(0.18, 0.82, 0.0, 1.0), glow)
        fill_coords(img, point_in_rect(0.38, 0.62, 0.0, 1.0), core)
    else:
        fill_coords(img, point_in_rect(0.15, 0.85, 0.15, 0.85), glow)
        fill_coords(img, point_in_rect(0.32, 0.68, 0.32, 0.68), core)


AGENT_SKIN_COLOUR = (240, 200, 165)
AGENT_INK_COLOUR = (30, 28, 32)


def _agent_sprite(agent_dir, color):
    """Pixel-art humanoid on a 32x32 grid -> (rgb, alpha).

    dir 0 faces the viewer (down), 1 = right profile, 2 = back view (up),
    3 = left profile, matching the direction the agent's beam fires.
    Side views are true profiles: narrow torso, one visible arm, striding
    legs and a nose bump."""
    g = 32
    rgb = onp.zeros((g, g, 3), dtype=onp.uint8)
    alpha = onp.zeros((g, g), dtype=bool)
    hair = tuple(int(c * 0.45) for c in color)
    pants = tuple(int(c * 0.62) for c in color)
    skin = AGENT_SKIN_COLOUR
    ink = AGENT_INK_COLOUR
    mouth = tuple(int(c * 0.8) for c in skin)

    def rect(x0, y0, x1, y1, col):
        rgb[y0:y1, x0:x1] = col
        alpha[y0:y1, x0:x1] = True

    if agent_dir in (0, 2):                       # front / back view
        rect(12, 22, 15, 27, pants)               # legs
        rect(17, 22, 20, 27, pants)
        rect(11, 27, 15, 29, ink)                 # feet
        rect(17, 27, 21, 29, ink)
        rect(9, 15, 12, 21, color)                # arms
        rect(20, 15, 23, 21, color)
        rect(9, 21, 12, 23, skin)                 # hands
        rect(20, 21, 23, 23, skin)
        rect(11, 14, 21, 22, color)               # torso
        rect(11, 5, 21, 13, skin)                 # head
        rect(10, 6, 11, 12, hair)
        rect(21, 6, 22, 12, hair)
        rect(11, 4, 21, 8, hair)                  # hair cap
        rect(10, 5, 11, 7, hair)
        rect(21, 5, 22, 7, hair)
        if agent_dir == 0:
            rect(13, 9, 15, 11, ink)              # eyes
            rect(17, 9, 19, 11, ink)
            rect(15, 12, 17, 13, mouth)
        else:
            rect(11, 4, 21, 13, hair)             # back of head
            rect(10, 5, 22, 12, hair)
    else:                                         # side profile
        rect(17, 22, 20, 26, pants)               # front leg
        rect(12, 22, 15, 27, pants)               # back leg
        rect(18, 26, 23, 28, ink)                 # front foot
        rect(10, 27, 15, 29, ink)                 # back foot
        rect(13, 14, 20, 22, color)               # narrow torso
        rect(17, 15, 20, 21, tuple(int(c * 0.78) for c in color))   # arm
        rect(18, 21, 21, 23, skin)                # hand
        rect(12, 5, 21, 13, skin)                 # head
        rect(21, 9, 22, 11, skin)                 # nose
        rect(12, 4, 21, 8, hair)                  # hair cap
        rect(11, 5, 13, 13, hair)                 # back hair
        rect(11, 12, 14, 14, hair)                # nape
        rect(17, 9, 19, 11, ink)                  # single eye
        rect(19, 12, 21, 13, mouth)

    if agent_dir == 3:                            # mirror for left facing
        rgb = rgb[:, ::-1].copy()
        alpha = alpha[:, ::-1].copy()
    return rgb, alpha


def draw_agent(img, agent_dir, color):
    """Blit the humanoid sprite (with a 1px outline) onto a tile image."""
    rgb, alpha = _agent_sprite(agent_dir, color)
    grown = alpha.copy()
    grown[1:, :] |= alpha[:-1, :]
    grown[:-1, :] |= alpha[1:, :]
    grown[:, 1:] |= alpha[:, :-1]
    grown[:, :-1] |= alpha[:, 1:]
    rgb[grown & ~alpha] = AGENT_OUTLINE_COLOUR

    scale = img.shape[0] // 32
    mask = onp.repeat(onp.repeat(grown, scale, 0), scale, 1)
    sprite = onp.repeat(onp.repeat(rgb, scale, 0), scale, 1)
    img[mask] = sprite[mask]

GREEN_COLOUR = (44.0, 160.0, 44.0)
RED_COLOUR = (214.0, 39.0, 40.0)
###################################################

class OpenHarvest(MultiAgentEnv):
    """
    JAX Compatible n-agent version of *inTheMatix environment.
    """

    # used for caching
    tile_cache: Dict[Tuple[Any, ...], Any]

    def __init__(
        self,
        num_inner_steps=1000,
        num_outer_steps=1,
        num_agents=7,
        inequity_aversion=False,
        inequity_aversion_target_agents=None,
        inequity_aversion_alpha=5,
        inequity_aversion_beta=0.05,
        enable_smooth_rewards=False,
        svo=False,
        svo_target_agents=None,
        svo_w=0.5,
        svo_ideal_angle_degrees=45,
        interest=False,
        s_interest=0.5,
        s_interest_schedule=None,
        s_interest_change_every=30000000,
        grid_size=(16,22),
        jit=True,
        obs_size=11,
        cnn=True,
        map_ASCII = [
                " RRR      YYY      GGG",
                "RRRRR   YYYYY    GGGGG",
                " RRR      YYY      GGG",
                "                      ",
                "                      ",
                "     CCC       MMM    ",
                "    CCCCC     MMMMM   ",
                "     CCC       MMM    ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
                "                      ",
                "  QQQQQQQQQQQQQQQQQQ  ",
                " PPPPPPPPPPPPPPPPPPPP ",
                "PPPPPPPPPPPPPPPPPPPPPP",
            ],
        rule_pool=None,          # RuleBenchmark (train or held-out half); None = sample the whole space
        ripen_steps=25,          # legacy: steps per ripeness stage when ripen_range is None
        ripen_range=(15, 20),    # each apple draws its own steps-per-stage from this closed range when it grows (2026-09-19); None = fixed ripen_steps
        initial_stage=0,         # stage of the apples the orchard is re-laid with
        value_levels=1,          # {1, ..., value_levels} per hue, shared by all agents; 1 = no per-hue value, reward depends on ripeness only (2026-09-16)
        fixed_values=None,       # (num_agents, num_hues) to pin the value tables (tests, oracles)
        fixed_rules=None,        # (speed_order (5,), pay_order (5,)) to pin the rules (tests, oracles)
        regrow_rates=None,       # override of discovery_rules.REGROW_RATES (3 multipliers for speed rank 0 / 1 / 2 = fast / normal / slow)
        regrow_base=None,        # base regrowth probability per step by hanging neighbours (>=3, 2, 1, 0); default = vanilla (0.025, 0.005, 0.001, 0)
        rot_regrow_steps=5,      # legacy: fixed countdown when rot_regrow_range is None
        rot_regrow_range=(2, 5), # a cell whose apple ROTTED regrows an unripe apple this many steps later (drawn per rot), whatever its neighbours (2026-09-19)
        zap_cooldown=2,          # steps after firing during which the beam is unavailable (Melting Pot 2.0 commons_harvest__open: cooldownTime = 2)
        frames_till_respawn=4,   # steps a zapped agent spends on its spawn cell unable to act (Melting Pot 2.0: framesTillRespawn = 4); 0 = vanilla SocialJax (act again immediately)
        stage_pay=None,          # override of discovery_rules.STAGE_PAY: points for pay rank 0 / 1 / 2 (default 1 / 0.5 / 0.25)
        random_patch_hues=True,  # every meta-episode draws a distinct hue for each patch slot (map letter), kept across its trials
        fixed_patch_hues=None,   # (num_slots,) hue per patch slot to pin the draw (tests, oracles); slot = index of the letter in RYGCMS
        patch_hues_with_replacement=False,   # draw each slot's hue independently (two patches can share a hue, a hue can be absent);
                                             # needed for maps with more patches than hues. Default: distinct hues, as before.
    ):

        super().__init__(num_agents=num_agents)
        self.agents = list(range(num_agents))#, dtype=jnp.int16)
        self._agents = jnp.array(self.agents, dtype=jnp.int16) + len(Items)
        self.cnn = cnn
        self.inequity_aversion = inequity_aversion
        self.inequity_aversion_target_agents = inequity_aversion_target_agents
        self.inequity_aversion_alpha = inequity_aversion_alpha
        self.inequity_aversion_beta = inequity_aversion_beta
        self.enable_smooth_rewards = enable_smooth_rewards
        self.svo = svo
        self.svo_target_agents = svo_target_agents
        self.svo_w = svo_w
        self.svo_ideal_angle_degrees = svo_ideal_angle_degrees
        self.smooth_rewards = enable_smooth_rewards
        self.interest = interest
        self.s_interest = s_interest
        # Convert schedule to JAX array for JIT compatibility
        if s_interest_schedule is not None:
            self.s_interest_schedule = jnp.array(s_interest_schedule)
        else:
            self.s_interest_schedule = None
        self.s_interest_change_every = s_interest_change_every

        # self.agents = [str(i) for i in list(range(num_agents))]

        self.PLAYER_COLOURS = generate_agent_colors(num_agents)
        # per-instance tile cache: cached agent colours depend on num_agents
        self.tile_cache = {}
        self.GRID_SIZE_ROW = grid_size[0]
        self.GRID_SIZE_COL = grid_size[1]
        self.OBS_SIZE = obs_size
        self.PADDING = self.OBS_SIZE - 1
        self.num_inner_steps = num_inner_steps
        self.num_outer_steps = num_outer_steps
        self.rule_pool = rule_pool
        self.ripen_lo, self.ripen_hi = (int(ripen_steps), int(ripen_steps)) if ripen_range is None else (int(ripen_range[0]), int(ripen_range[1]))
        self.ripen_steps = (self.ripen_lo + self.ripen_hi) / 2          # mean, for code that wants one number (oracles)
        self.initial_stage = int(initial_stage)
        self.value_levels = int(value_levels)
        self.num_hues = NUM_HARVEST_HUES
        self.fixed_values = None if fixed_values is None else jnp.asarray(fixed_values, dtype=jnp.uint8)
        self.fixed_rules = None if fixed_rules is None else (jnp.asarray(fixed_rules[0], dtype=jnp.uint8), jnp.asarray(fixed_rules[1], dtype=jnp.uint8))
        self.REGROW_RATES = jnp.asarray(REGROW_RATES if regrow_rates is None else regrow_rates, dtype=jnp.float32)
        self.RATE_TABLE = jnp.array([[float(self.REGROW_RATES[r]) for r in o] for o in PAY_ORDERS], dtype=jnp.float32)   # (speed order, stage the last apple left at) -> multiplier
        self.REGROW_BASE = jnp.asarray((0.025, 0.005, 0.001, 0.0) if regrow_base is None else regrow_base, dtype=jnp.float32)   # by hanging neighbours >=3 / 2 / 1 / 0
        self.rot_lo, self.rot_hi = (int(rot_regrow_steps), int(rot_regrow_steps)) if rot_regrow_range is None else (int(rot_regrow_range[0]), int(rot_regrow_range[1]))
        self.rot_regrow_steps = (self.rot_lo + self.rot_hi) / 2
        self.zap_cooldown = int(zap_cooldown)
        self.frames_till_respawn = int(frames_till_respawn)
        pay = STAGE_PAY if stage_pay is None else tuple(float(x) for x in stage_pay)
        self.PAY_TABLE = jnp.array([[pay[r] for r in o] for o in PAY_ORDERS], dtype=jnp.float32)   # (pay order, stage) -> points
        self.random_patch_hues = bool(random_patch_hues)
        self.patch_hues_with_replacement = bool(patch_hues_with_replacement)
        self.fixed_patch_hues = None if fixed_patch_hues is None else jnp.asarray(fixed_patch_hues, dtype=jnp.int32)

        GRID = jnp.zeros(
            (self.GRID_SIZE_ROW + 2 * self.PADDING, self.GRID_SIZE_COL + 2 * self.PADDING),
            dtype=jnp.int16,
        )

        # First layer of padding is Wall
        GRID = GRID.at[self.PADDING - 1, :].set(5)
        GRID = GRID.at[self.GRID_SIZE_ROW + self.PADDING, :].set(5)
        GRID = GRID.at[:, self.PADDING - 1].set(5)
        self.GRID = GRID.at[:, self.GRID_SIZE_COL + self.PADDING].set(5)

        def find_positions(grid_array, letter):
            a_positions = jnp.array(jnp.where(grid_array == letter)).T
            return a_positions

        assert all(len(r) <= grid_size[1] for r in map_ASCII) and len(map_ASCII) <= grid_size[0], "map_ASCII does not fit grid_size"
        nums_map = ascii_map_to_matrix(map_ASCII, char_to_int)
        # apple cells: generic 'A' (hue 0) and the single-hue patch letters; APPLE_HUES[i] is the hue of cell i
        nums_np = onp.asarray(nums_map)
        apple_mask = (nums_np == 3) | ((nums_np >= _MAP_HUE_CODE) & (nums_np < _MAP_HUE_CODE + len(SLOT_LETTERS)))
        rows_, cols_ = onp.nonzero(apple_mask)
        self.SPAWNS_APPLE = jnp.asarray(onp.stack([rows_, cols_], axis=1), dtype=jnp.int32)
        # APPLE_SLOTS[i] = patch slot of cell i (index of its map letter in RYGCM; generic 'A' = slot 0). The hue of a slot is
        # drawn per meta-episode into State.cell_hues; APPLE_HUES / HUE_OF_CELL are the undrawn identity mapping (legacy).
        self.APPLE_SLOTS = jnp.asarray(onp.where(nums_np[rows_, cols_] == 3, 0, nums_np[rows_, cols_] - _MAP_HUE_CODE), dtype=jnp.int32)
        self.NUM_SLOTS = int(onp.asarray(self.APPLE_SLOTS).max()) + 1
        assert self.NUM_SLOTS <= NUM_HARVEST_HUES or self.patch_hues_with_replacement or fixed_patch_hues is not None, \
            "more patch slots than hues: draw the hues with replacement (or pin them)"
        self.APPLE_HUES = self.APPLE_SLOTS
        self.HUE_OF_CELL = jnp.zeros((self.GRID_SIZE_ROW, self.GRID_SIZE_COL), dtype=jnp.int32).at[rows_, cols_].set(self.APPLE_HUES)
        self.SPAWNS_PLAYER_IN = find_positions(nums_map, 5)
        self.SPAWNS_PLAYERS = find_positions(nums_map, 4)
        assert len(self.SPAWNS_PLAYERS) >= num_agents, "need at least num_agents spawn cells for occupancy-aware respawn"
        self.SPAWNS_WALL = find_positions(nums_map, 1)


        def rand_interaction(
                key: int,
                conflicts: jnp.ndarray,
                conflicts_matrix: jnp.ndarray,
                step_arr: jnp.ndarray
            ) -> jnp.ndarray:
            '''
            Function for randomly choosing between conflicting interactions.
            
            Args:
                - key: jax PRNGKey for randomisation.
                - conflicts: jnp.ndarray of bools where True if agent is in a
                conflicting interaction, False otherwise.
                - conflicts_matrix: jnp.ndarray matrix of bools of agents in
                conflicting interactions.
                - step_arr: jnp.ndarray, where each index is the index of an
                agent, and the element at each index is the item found at that
                agent's respective target location in the grid.

                
            Returns:
                - jnp.ndarray array of final interactions, where each index is
                an agent, and each element is caught in its interaction beam.
            '''
            def scan_fn(
                    state,
                    idx
            ):

                key, conflicts, conflicts_matrix, step_arr = state

                return jax.lax.cond(
                    conflicts[idx] > 0,
                    lambda: _rand_interaction(
                        key,
                        conflicts,
                        conflicts_matrix,
                        step_arr
                    ),
                    lambda: (state, step_arr.astype(jnp.int16))
                )

            _, ys = jax.lax.scan(
                scan_fn,
                (key, conflicts, conflicts_matrix, step_arr.astype(jnp.int16)),
                jnp.arange(self.num_agents)
            )

            final_itxs = ys[-1]
            return final_itxs

        def _rand_interaction(
                key: int,
                conflicts: jnp.ndarray,
                conflicts_matrix: jnp.ndarray,
                step_arr: jnp.ndarray
            ) -> jnp.ndarray:
            '''
            Function for randomly choosing between conflicting interactions.
            
            Args:
                - key: jax PRNGKey for randomisation.
                - conflicts: jnp.ndarray of bools where True if agent is in a
                conflicting interaction, False otherwise.
                - conflicts_matrix: jnp.ndarray matrix of bools of agents in
                conflicting interactions.
                - step_arr: jnp.ndarray, where each index is the index of an
                agent, and the element at each index is the item found at that
                agent's respective target location in the grid.

                
            Returns:
                - jnp.ndarray array of final interactions, where each index is
                an agent, and each element is caught in its interaction beam.
            '''
            conflict_idx = jnp.nonzero(
                conflicts,
                size=self.num_agents,
                fill_value=-1
            )[0][0]

            agent_conflicts = conflicts_matrix[conflict_idx]

            agent_conflicts_idx = jnp.nonzero(
                agent_conflicts,
                size=self.num_agents,
                fill_value=-1
            )[0]
            max_rand = jnp.sum(agent_conflicts_idx > -1)

            # preparing random agent selection
            k1, k2 = jax.random.split(key, 2)
            random_number = jax.random.randint(
                k1,
                (1,),
                0,
                max_rand
            )

            # index in main matrix of agent of successful interaction
            rand_agent_idx = agent_conflicts_idx[random_number]

            # set that agent's bool to False, for inversion later
            new_agent_conflict = agent_conflicts.at[rand_agent_idx].set(False)

            # set all remaining True agents' values as the "empty" item
            step_arr = jnp.where(
                new_agent_conflict,
                Items.empty,
                step_arr
            ).astype(jnp.int16)

            # update conflict bools to reflect the post-conflict state
            _conflicts = conflicts.at[agent_conflicts_idx].set(0)
            conflicts = jnp.where(
                agent_conflicts,
                0,
                conflicts
            )
            conflicts = conflicts.at[conflict_idx].set(0)
            conflicts_matrix = jax.vmap(
                lambda c, x: jnp.where(c, x, jnp.array([False]*conflicts.shape[0]))
            )(conflicts, conflicts_matrix)

            # deal with next conflict
            return ((
                k2,
                conflicts,
                conflicts_matrix,
                step_arr
            ), step_arr)
        
        
        # first attempt at func - needs improvement
        # inefficient due to double-checking collisions
        def check_interaction_conflict(
                items: jnp.ndarray
            ) -> jnp.ndarray:
            '''
            Function to check conflicting interaction targets.
            
            Args:
                - items: jnp.ndarray, the agent itemss at the interaction
                targets.
                
            Returns:
                - jnp.ndarray matrix of bool of agents in collision.
            '''
            matcher = jax.vmap(
                lambda x,y: jnp.logical_and(
                    jnp.all(x == y),
                    jnp.isin(x, self._agents)
                ),
                in_axes=(0, None)
            )

            collisions = jax.vmap(
                matcher,
                in_axes=(None, 0)
            )(items, items)

            return collisions



        
        def combine_channels(
                grid: jnp.ndarray,
                agent: int,
                angles: jnp.ndarray,
                agent_pickups: jnp.ndarray,
                state: State,
            ):
            '''
            Function to enforce symmetry in observations & generate final
            feature representation; current agent is permuted to first 
            position in the feature dimension.
            
            Args:
                - grid: jax ndarray of current agent's obs grid
                - agent: int, an index indicating current agent number
                - angles: jnp.ndarray of current agents' relative orientation
                in current agent's obs grid
                - agent_pickups: jnp.ndarray of agents able to interact
                - state: State, the env state obj
            Returns:
                - grid with current agent [x] permuted to 1st position (after
                the first 4 "Items" features, so 5th position overall) in the
                feature dimension, "other" [x] agent 2nd, angle [x, x, x, x]
                3rd, pick-up [x] bool 4th, inventory [x, x] 5th, frozen [x]
                6th, for a final obs grid of shape (5, 5, 14) (additional 4
                one-hot places for 5 possible items)
            '''
            def move_and_collapse(
                    x: jnp.ndarray,
                    angle: jnp.ndarray,
                ) -> jnp.ndarray:

                # get agent's one-hot
                agent_element = jnp.array([jnp.int8(x[agent])])

                # mask to check if any other agent exists there
                mask = x[len(Items)-1:] > 0

                # does an agent exist which is not the subject?
                other_agent = jnp.int8(
                    jnp.logical_and(
                        jnp.any(mask),
                        jnp.logical_not(
                            agent_element
                        )
                    )
                )

                # what is the class of the item in cell
                item_idx = jnp.where(
                    x,
                    size=1
                )[0]

                # check if agent is frozen and can observe inventories
                show_inv_bool = jnp.logical_and(
                        state.freeze[
                            agent-len(Items)
                        ].max(axis=-1) > 0,
                        item_idx >= len(Items)
                )

                show_inv_idxs = jnp.where(
                    state.freeze[agent],
                    size=12, # since, in a setting where simultaneous interac-
                    fill_value=-1 # -tions can happen, only a max of 12 can
                )[0] # happen at once (zap logic), regardless of pop size

                inv_to_show = jnp.where(
                    jnp.logical_or(
                        jnp.logical_and(
                            show_inv_bool,
                            jnp.isin(item_idx-len(Items), show_inv_idxs),
                        ),
                        agent_element
                    ),
                    state.agent_invs[item_idx - len(Items)],
                    jnp.array([0, 0], dtype=jnp.int8)
                )[0]

                # check if agent is not the subject & is frozen & therefore
                # not possible to interact with
                frozen = jnp.where(
                    other_agent,
                    state.freeze[
                        item_idx-len(Items)
                    ].max(axis=-1) > 0,
                    0
                )

                # get pickup/inv info
                pick_up_idx = jnp.where(
                    jnp.any(mask),
                    jnp.nonzero(mask, size=1)[0],
                    jnp.int8(-1)
                )
                picked_up = jnp.where(
                    pick_up_idx > -1,
                    agent_pickups[pick_up_idx],
                    jnp.int8(0)
                )

                # build extension
                extension = jnp.concatenate(
                    [
                        agent_element,
                        other_agent,
                        angle,
                        picked_up,
                        inv_to_show,
                        frozen
                    ],
                    axis=-1
                )

                # build final feature vector
                final_vec = jnp.concatenate(
                    [x[:len(Items)-1], extension],
                    axis=-1
                )

                return final_vec

            new_grid = jax.vmap(
                jax.vmap(
                    move_and_collapse
                )
            )(grid, angles)
            return new_grid
        
        def check_relative_orientation(
                agent: int,
                agent_locs: jnp.ndarray,
                grid: jnp.ndarray
            ) -> jnp.ndarray:
            '''
            Check's relative orientations of all other agents in view of
            current agent.
            
            Args:
                - agent: int, an index indicating current agent number
                - agent_locs: jax ndarray of agent locations (x, y, direction)
                - grid: jax ndarray of current agent's obs grid
                
            Returns:
                - grid with 1) int -1 in places where no agent exists, or
                where the agent is the current agent, and 2) int in range
                0-3 in cells of opposing agents indicating relative
                orientation to current agent.
            '''
            # we decrement by num of Items when indexing as we incremented by
            # 5 in constructor call (due to 5 non-agent Items enum & locations
            # are indexed from 0)
            idx = agent - len(Items)
            agents = jnp.delete(
                self._agents,
                idx,
                assume_unique_indices=True
            )
            curr_agent_dir = agent_locs[idx, 2]

            def calc_relative_direction(cell):
                cell_agent = cell - len(Items)
                cell_direction = agent_locs[cell_agent, 2]
                return (cell_direction - curr_agent_dir) % 4

            angle = jnp.where(
                jnp.isin(grid, agents),
                jax.vmap(calc_relative_direction)(grid),
                -1
            )

            return angle
        
        def rotate_grid(agent_loc: jnp.ndarray, grid: jnp.ndarray) -> jnp.ndarray:
            '''
            Rotates agent's observation grid k * 90 degrees, depending on agent's
            orientation.

            Args:
                - agent_loc: jax ndarray of agent's x, y, direction
                - grid: jax ndarray of agent's obs grid

            Returns:
                - jnp.ndarray of new rotated grid.

            '''
            grid = jnp.where(
                agent_loc[2] == 1,
                jnp.rot90(grid, k=1, axes=(0, 1)),
                grid,
            )
            grid = jnp.where(
                agent_loc[2] == 2,
                jnp.rot90(grid, k=2, axes=(0, 1)),
                grid,
            )
            grid = jnp.where(
                agent_loc[2] == 3,
                jnp.rot90(grid, k=3, axes=(0, 1)),
                grid,
            )

            return grid

        def _get_obs_point(agent_loc: jnp.ndarray) -> jnp.ndarray:
            '''
            Obtain the position of top-left corner of obs map using
            agent's current location & orientation.

            Args: 
                - agent_loc: jnp.ndarray, agent x, y, direction.
            Returns:
                - x, y: ints of top-left corner of agent's obs map.
            '''
            
            x, y, direction = agent_loc

            x, y = x + self.PADDING, y + self.PADDING

            x = x - (self.OBS_SIZE // 2)
            y = y - (self.OBS_SIZE // 2)


            x = jnp.where(direction == 0, x + (self.OBS_SIZE//2)-1, x)
            y = jnp.where(direction == 0, y, y)

            x = jnp.where(direction == 1, x, x)
            y = jnp.where(direction == 1, y + (self.OBS_SIZE//2)-1, y)


            x = jnp.where(direction == 2, x - (self.OBS_SIZE//2)+1, x)
            y = jnp.where(direction == 2, y, y)


            x = jnp.where(direction == 3, x, x)
            y = jnp.where(direction == 3, y - (self.OBS_SIZE//2)+1, y)


            return x, y

        def _get_obs(state: State) -> jnp.ndarray:
            '''
            Obtain the agent's observation of the grid.

            Args: 
                - state: State object containing env state.
            Returns:
                - jnp.ndarray of grid observation.
            '''
            # create state
            grid = jnp.pad(
                state.grid,
                ((self.PADDING, self.PADDING), (self.PADDING, self.PADDING)),
                constant_values=Items.wall,
            )

            # obtain all agent obs-points
            agent_start_idxs = jax.vmap(_get_obs_point)(state.agent_locs)

            dynamic_slice = partial(
                jax.lax.dynamic_slice,
                operand=grid,
                slice_sizes=(self.OBS_SIZE, self.OBS_SIZE)
            )

            # obtain agent obs grids
            grids = jax.vmap(dynamic_slice)(start_indices=agent_start_idxs)

            # rotate agent obs grids
            grids = jax.vmap(rotate_grid)(state.agent_locs, grids)

            angles = jax.vmap(
                check_relative_orientation,
                in_axes=(0, None, 0)
            )(
                self._agents,
                state.agent_locs,
                grids
            )

            angles = jax.nn.one_hot(angles, 4)

            # one-hot (drop first channel as its empty blocks)
            grids = jax.nn.one_hot(
                grids - 1,
                num_agents + len(Items) - 1, # will be collapsed into a
                dtype=jnp.int8 # [Items, self, other, extra features] representation
            )

            # check agents that can interact
            inventory_sum = jnp.sum(state.agent_invs, axis=-1)
            agent_pickups = jnp.where(
                inventory_sum > INTERACT_THRESHOLD,
                True,
                False
            )

            # make index len(Item) always the current agent
            # and sum all others into an "other" agent
            grids = jax.vmap(
                combine_channels,
                in_axes=(0, 0, 0, None, None)
            )(
                grids,
                self._agents,
                angles,
                agent_pickups,
                state
            )

            return grids

        def _interact(
            key: jnp.ndarray, state: State, actions: jnp.ndarray
        ) -> Tuple[jnp.ndarray, jnp.ndarray, State, jnp.ndarray]:
            '''
            Main interaction logic entry point.

            Args:
                - key: jax key for randomisation.
                - state: State env state object.
                - actions: jnp.ndarray of actions taken by agents.
            Returns:
                - (jnp.ndarray, State, jnp.ndarray) - Tuple where index 0 is
                the array of rewards obtained, index 2 is the new env State,
                and index 3 is the new freeze penalty matrix.
            '''
            # if interact
            zaps = jnp.isin(actions,
                jnp.array(
                    [
                        Actions.zap_forward,
                        # Actions.zap_ahead
                    ]
                )
            )

            interact_idx = jnp.int16(Items.interact)

            # remove old interacts
            state = state.replace(grid=jnp.where(
                state.grid == interact_idx, jnp.int16(Items.empty), state.grid))


            def check_valid_zap(t, i):
                '''
                Check target agent exists, isn't frozen, can interact, and
                is not the zapping-agent's self.
                '''
                agnt_bool = jnp.isin(state.grid[t[0], t[1]], self._agents)
                self_bool = state.grid[t[0], t[1]] != i
            
                return jnp.logical_and(agnt_bool, self_bool)

            # check 1 ahead
            clip_row = partial(jnp.clip, a_min=0, a_max=self.GRID_SIZE_ROW - 1)
            clip_col = partial(jnp.clip, a_min=0, a_max=self.GRID_SIZE_COL - 1)

            one_step_targets = jax.vmap(
                lambda p: p + STEP[p[2]]
            )(state.agent_locs)

            # one_step_targets = jax.vmap(clip)(one_step_targets)
            # one_step_targets[:,0] = jax.vmap(clip_row)(one_step_targets[:,0])
            # one_step_targets[:,1] = jax.vmap(clip_col)(one_step_targets[:,1])

            one_step_interacts = jax.vmap(
                check_valid_zap
            )(t=one_step_targets, i=self._agents)

            # check 2 ahead
            two_step_targets = jax.vmap(
                lambda p: p + 2*STEP[p[2]]
            )(state.agent_locs)

            # two_step_targets = jax.vmap(clip)(two_step_targets)
            # two_step_targets[:,0] = jax.vmap(clip_row)(two_step_targets[:,0])
            # two_step_targets[:,1] = jax.vmap(clip_col)(two_step_targets[:,1])

            two_step_interacts = jax.vmap(
                check_valid_zap
            )(t=two_step_targets, i=self._agents)

            # check forward-right & manually check out-of-bounds
            target_right = jax.vmap(
                lambda p: p + STEP[p[2]] + STEP[(p[2] + 1) % 4]
            )(state.agent_locs)

            right_oob_check = jax.vmap(
                lambda t: jnp.logical_or(
                    jnp.logical_or((t[0] > self.GRID_SIZE_ROW - 1).any(), (t[1] > self.GRID_SIZE_COL - 1).any()),
                    (t < 0).any(),
                )
            )(target_right)

            target_right = jnp.where(
                right_oob_check[:, None],
                one_step_targets,
                target_right
            )

            right_interacts = jax.vmap(
                check_valid_zap
            )(t=target_right, i=self._agents)

            # check forward-left & manually check out-of-bounds
            target_left = jax.vmap(
                lambda p: p + STEP[p[2]] + STEP[(p[2] - 1) % 4]
            )(state.agent_locs)

            left_oob_check = jax.vmap(
                lambda t: jnp.logical_or(
                    jnp.logical_or((t[0] > self.GRID_SIZE_ROW - 1).any(), (t[1] > self.GRID_SIZE_COL - 1).any()),
                    (t < 0).any(),
                )
            )(target_left)

            target_left = jnp.where(
                left_oob_check[:, None],
                one_step_targets,
                target_left
            )

            left_interacts = jax.vmap(
                check_valid_zap
            )(t=target_right, i=self._agents)


            # one_step_targets_exd = jnp.expand_dims(one_step_targets, axis=0)
            # two_step_targets_exd = jnp.expand_dims(two_step_targets, axis=0)
            # target_right_exd = jnp.expand_dims(target_right, axis=0)
            # target_left_exd = jnp.expand_dims(target_left, axis=0)


            # A beam cell outside the grid hits nothing. Without this, a negative index wraps to the far side of the
            # map (firing north from the top rows hit the bottom rows) and a too-large one clamps onto the edge. Park
            # such targets far out of range, where scatters drop them, and mask them out of every hit test.
            def _in_grid(t):
                return (t[:, 0] >= 0) & (t[:, 0] < self.GRID_SIZE_ROW) & (t[:, 1] >= 0) & (t[:, 1] < self.GRID_SIZE_COL)
            _off = jnp.array([self.GRID_SIZE_ROW + 100, self.GRID_SIZE_COL + 100, 0], dtype=one_step_targets.dtype)
            one_ok, two_ok, right_ok, left_ok = (_in_grid(t) for t in (one_step_targets, two_step_targets, target_right, target_left))
            one_step_targets = jnp.where(one_ok[:, None], one_step_targets, _off)
            two_step_targets = jnp.where(two_ok[:, None], two_step_targets, _off)
            target_right = jnp.where(right_ok[:, None], target_right, _off)
            target_left = jnp.where(left_ok[:, None], target_left, _off)
            beam_in_grid = jnp.concatenate((one_ok, two_ok, right_ok, left_ok), 0)

            all_zaped_locs = jnp.concatenate((one_step_targets, two_step_targets, target_right, target_left), 0)
            # zaps_3d = jnp.stack([zaps, zaps, zaps], axis=-1)

            zaps_4_locs = jnp.concatenate((zaps, zaps, zaps, zaps), 0) & beam_in_grid


            # all_zaped_locs = jax.vmap(filter_zaped_locs)(all_zaped_locs)

            def zaped_gird(a, z):
                return jnp.where(z, state.grid[a[0], a[1]], -1)

            all_zaped_gird = jax.vmap(zaped_gird)(all_zaped_locs, zaps_4_locs)
            

            def check_reborn_player(a):
                return jnp.isin(a, all_zaped_gird)
            
            reborn_players = jax.vmap(check_reborn_player)(self._agents)
            # jax.debug.print("reborn_players {reborn_players} 🤯", reborn_players=reborn_players)

            # all interacts = whether there is an agent at target & whether
            # agent is not frozen already & is qualified to interact
            # all_interacts = jnp.concatenate(
            #     [
            #         jnp.expand_dims(one_step_interacts, axis=-1),
            #         jnp.expand_dims(two_step_interacts, axis=-1),
            #         jnp.expand_dims(right_interacts, axis=-1),
            #         jnp.expand_dims(left_interacts, axis=-1)
            #     ],
            #     axis=-1
            # )
            # jax.debug.print("all_interacts {all_interacts} 🤯", all_interacts=all_interacts)

            # def check_reborn_players(i):
            #     return jnp.any(all_interacts[i,:] == True)
            
            # exists_vector = jax.vmap(check_reborn_players)(self._agents-6)

            # reborn_players = jnp.where(exists_vector is True, self._agents, -1)


            # interact_idxs = jnp.clip(actions - Actions.zap_forward, 0, 3)

            # all_interacts = all_interacts[jnp.arange(all_interacts.shape[0]), interact_idxs]# * zaps * agent_pickups * (state.freeze.max(axis=-1) <= 0)

            # update grid with all zaps
            aux_grid = jnp.copy(state.grid)

            o_items = jnp.where(
                        state.grid[
                            one_step_targets[:, 0],
                            one_step_targets[:, 1]
                        ],
                        state.grid[
                            one_step_targets[:, 0],
                            one_step_targets[:, 1]
                        ],
                        interact_idx
                    )

            t_items = jnp.where(
                        state.grid[
                            two_step_targets[:, 0],
                            two_step_targets[:, 1]
                        ],
                        state.grid[
                            two_step_targets[:, 0],
                            two_step_targets[:, 1]
                        ],
                        interact_idx
                    )

            r_items = jnp.where(
                        state.grid[
                            target_right[:, 0],
                            target_right[:, 1]
                        ],
                        state.grid[
                            target_right[:, 0],
                            target_right[:, 1]
                        ],
                        interact_idx
                    )

            l_items = jnp.where(
                        state.grid[
                            target_left[:, 0],
                            target_left[:, 1]
                        ],
                        state.grid[
                            target_left[:, 0],
                            target_left[:, 1]
                        ],
                        interact_idx
                    )

            qualified_to_zap = zaps.reshape(-1)
            # jax.debug.print("qualified_to_zap {qualified_to_zap} 🤯", qualified_to_zap=qualified_to_zap)
            # update grid
            def update_grid(a_i, t, i, grid):
                return grid.at[t[:, 0], t[:, 1]].set(
                    jax.vmap(jnp.where)(
                        a_i,
                        i,
                        aux_grid[t[:, 0], t[:, 1]]
                    )
                )
            # def update_grid(a_i, t, i, grid):
            #     return grid.at[t[:, 0], t[:, 1]].set(2)


            # jax.debug.print("one_step_targets {one_step_targets} 🤯", one_step_targets=one_step_targets)
            aux_grid = update_grid(qualified_to_zap, one_step_targets, o_items, aux_grid)
            aux_grid = update_grid(qualified_to_zap, two_step_targets, t_items, aux_grid)
            aux_grid = update_grid(qualified_to_zap, target_right, r_items, aux_grid)
            aux_grid = update_grid(qualified_to_zap, target_left, l_items, aux_grid)

            # jax.debug.print("aux_grid {aux_grid} 🤯", aux_grid=aux_grid)
            state = state.replace(
                grid=jnp.where(
                    jnp.any(zaps),
                    aux_grid,
                    state.grid
                )
            )


            return reborn_players, state

        def get_current_s_interest(timestep):
            """Calculate current s_interest based on timestep and schedule."""
            if self.s_interest_schedule is None:
                return self.s_interest

            # Calculate which phase we're in using JAX operations
            phase = timestep // self.s_interest_change_every
            phase_idx = phase % self.s_interest_schedule.shape[0]
            return self.s_interest_schedule[phase_idx]

        def _step(
            key: chex.PRNGKey,
            state: State,
            actions: jnp.ndarray,
            timestep: int = 0
        ):
            """Step the environment."""
            # actions = self.action_set.take(indices=jnp.array([actions["0"], actions["agent_1"]]))
            actions = jnp.array(actions)

            zap_frozen = state.zap_wait > 0                      # sent back by a beam: off the game for a few steps
            actions = jnp.where(zap_frozen, jnp.asarray(Actions.stay, actions.dtype), actions)
            actions = jnp.where((state.zap_cd > 0) & (actions == Actions.zap_forward),
                                jnp.asarray(Actions.stay, actions.dtype), actions)   # beam still cooling down

            # freeze check
            # actions = jnp.where(
            #     state.freeze.max(axis=-1) > 0,
            #     Actions.stay,
            #     actions
            # )

            # regrow apple (vanilla neighbour counting; any hue/stage counts as an apple)
            grid_apple = state.grid
            ga = is_apple(grid_apple)
            rate_idx, order = decode_harvest_ruleset(state.rule_encoding, self.num_hues)
            cell_rate = self.RATE_TABLE[rate_idx[state.cell_hues], state.last_stage]   # (num_apple_cells,): speed set by the stage the last apple left at

            def count_apple(apple_locs):

                apple_nums = jnp.where((ga[apple_locs[0]-1, apple_locs[1]]) & (apple_locs[0]-1 >=0), 1, 0) + \
                                jnp.where((ga[apple_locs[0]+1, apple_locs[1]]) & (apple_locs[0]+1 < self.GRID_SIZE_ROW), 1, 0) + \
                                jnp.where((ga[apple_locs[0], apple_locs[1]-1]) & (apple_locs[1]-1 >=0), 1, 0) + \
                                jnp.where((ga[apple_locs[0], apple_locs[1]+1]) & (apple_locs[1]+1 < self.GRID_SIZE_COL), 1, 0)+ \
                                jnp.where((ga[apple_locs[0]-2, apple_locs[1]]) & (apple_locs[0]-2 >=0), 1, 0) + \
                                jnp.where((ga[apple_locs[0]+2, apple_locs[1]]) & (apple_locs[0]+2 < self.GRID_SIZE_ROW), 1 ,0) + \
                                jnp.where((ga[apple_locs[0], apple_locs[1]-2]) & (apple_locs[1]-2 >=0), 1, 0) + \
                                jnp.where((ga[apple_locs[0], apple_locs[1]+2]) & (apple_locs[1]+2 < self.GRID_SIZE_COL), 1 ,0) + \
                                jnp.where((ga[apple_locs[0]-1, apple_locs[1]-1]) & (apple_locs[0]-1 >=0) & (apple_locs[1]-1 >=0), 1, 0) + \
                                jnp.where((ga[apple_locs[0]-1, apple_locs[1]+1]) & (apple_locs[0]-1 >=0) & (apple_locs[1]+1 < self.GRID_SIZE_COL), 1, 0) + \
                                jnp.where((ga[apple_locs[0]+1, apple_locs[1]-1]) & (apple_locs[1]+1 < self.GRID_SIZE_COL) & (apple_locs[1]-1 >=0), 1, 0) + \
                                jnp.where((ga[apple_locs[0]+1, apple_locs[1]+1]) & (apple_locs[0]+1 < self.GRID_SIZE_ROW) & (apple_locs[1]+1 < self.GRID_SIZE_COL) , 1, 0)
                
                return apple_nums

            near_apple_nums = jax.vmap(count_apple)(self.SPAWNS_APPLE)
            
            # grid_apple = state.grid

            def regrow_apple(apple_locs, near_apple, prob, rate, hue, age, last_stage, ripen_len, ripen_draw, rot_draw):
                cell = grid_apple[apple_locs[0], apple_locs[1]]
                empty = cell == Items.empty
                # vanilla thresholds x the hidden speed of this cell (hue's order applied to the stage its last apple left at)
                base = self.REGROW_BASE[jnp.clip(3 - near_apple, 0, 3)]      # vanilla: 2.5% / 0.5% / 0.1% / 0 for >=3 / 2 / 1 / 0 hanging neighbours
                pending = empty & (age < 0)                                    # counting down after a rot
                grows = empty & ((prob < base * rate) | (age == -1))            # chance regrowth, or the rot countdown ran out
                hanging = is_apple(cell)
                new_age = jnp.where(hanging, age + 1, jnp.where(pending, age + 1, 0))
                rotten = hanging & (new_age >= NUM_RIPE_STAGES * ripen_len)
                stage = jnp.minimum(new_age // ripen_len, NUM_RIPE_STAGES - 1)
                ripened = APPLE_BASE + hue * NUM_RIPE_STAGES + stage
                new_cell = jnp.where(grows, APPLE_BASE + hue * NUM_RIPE_STAGES,
                                     jnp.where(hanging & ~rotten, ripened, jnp.where(hanging & rotten, Items.empty, cell)))
                new_age = jnp.where(rotten, -rot_draw, jnp.where(grows, 0, new_age))   # rot starts a countdown drawn from rot_regrow_range; a new apple starts at age 0
                new_last = jnp.where(rotten, NUM_RIPE_STAGES - 1, last_stage)      # a rotted apple counts as having left at over-ripe
                new_len = jnp.where(grows, ripen_draw, ripen_len)                   # a new apple draws its own steps per stage
                return new_cell.astype(jnp.int16), new_age.astype(jnp.int16), new_last.astype(jnp.int8), new_len.astype(jnp.int16)

            prob = jax.random.uniform(key, shape=(len(self.SPAWNS_APPLE),))
            # the per-apple draws use fold_in so the existing random stream is untouched: with degenerate ranges the env replays old logs bit for bit
            ripen_draw = jax.random.randint(jax.random.fold_in(key, 11), (len(self.SPAWNS_APPLE),), self.ripen_lo, self.ripen_hi + 1)
            rot_draw = jax.random.randint(jax.random.fold_in(key, 12), (len(self.SPAWNS_APPLE),), self.rot_lo, self.rot_hi + 1)
            new_apple, new_age, new_last, new_len = jax.vmap(regrow_apple)(self.SPAWNS_APPLE, near_apple_nums, prob, cell_rate, state.cell_hues, state.age, state.last_stage,
                                                                           state.ripen_len, ripen_draw, rot_draw)
            # a cell currently under an agent keeps the agent code (its apple was eaten on arrival)
            under_agent = grid_apple[self.SPAWNS_APPLE[:, 0], self.SPAWNS_APPLE[:, 1]] >= len(Items)
            new_apple = jnp.where(under_agent, grid_apple[self.SPAWNS_APPLE[:, 0], self.SPAWNS_APPLE[:, 1]], new_apple)
            new_age = jnp.where(under_agent, jnp.where(state.age < 0, jnp.minimum(state.age + 1, -1), 0), new_age)   # an occupied cell keeps its rot countdown (held at -1 until free)
            new_apple_grid = grid_apple.at[self.SPAWNS_APPLE[:, 0], self.SPAWNS_APPLE[:, 1]].set(new_apple[:])
            state = state.replace(grid=new_apple_grid, age=new_age, last_stage=new_last, ripen_len=jnp.where(under_agent, state.ripen_len, new_len))

            # moving all agents

            new_grid = state.grid.at[
                state.agent_locs[:, 0],
                state.agent_locs[:, 1]
            ].set(
                jnp.int16(Items.empty)
            )

            x, y = state.reborn_locs[:, 0], state.reborn_locs[:, 1]
            new_grid = new_grid.at[x, y].set(self._agents)
            state = state.replace(grid=new_grid)
            state = state.replace(agent_locs=state.reborn_locs)

            # state = state.replace(reborn_locs=state.agent_locs)

            key, subkey = jax.random.split(key)
            all_new_locs = jax.vmap(lambda p, a: jnp.int16(p + ROTATIONS[a]) % jnp.array([self.GRID_SIZE_ROW + 1, self.GRID_SIZE_COL + 1, 4], dtype=jnp.int16))(p=state.agent_locs, a=actions).reshape(-1, 3)

            agent_move = (actions == Actions.up) | (actions == Actions.down) | (actions == Actions.right) | (actions == Actions.left)
            all_new_locs = jax.vmap(lambda m, n, p: jnp.where(m, n + STEP_MOVE[p], n))(m=agent_move, n=all_new_locs, p=actions)
            
            all_new_locs = jax.vmap(
                jnp.clip,
                in_axes=(0, None, None)
            )(
                all_new_locs,
                jnp.array([0, 0, 0], dtype=jnp.int16),
                jnp.array(
                    [self.GRID_SIZE_ROW - 1, self.GRID_SIZE_COL - 1, 3],
                    dtype=jnp.int16
                ),
            ).reshape(-1, 3)

            # Block impassable cells (anything that is not empty/apple/an
            # agent stamp) BEFORE conflict resolution; cells currently
            # holding an agent (grid code >= len(Items)) stay passable so
            # trains/following can work.
            target_cells = state.grid[all_new_locs[:, 0], all_new_locs[:, 1]]
            blocked = ((target_cells != Items.empty) &
                       ~is_apple(target_cells) &
                       (target_cells < len(Items)))
            all_new_locs = jnp.where(blocked[:, None], state.agent_locs, all_new_locs)

            # Resolve agent-agent movement conflicts via the shared
            # resolver: same-target conflicts (non-mover priority, else
            # random winner), swaps blocked, trains allowed, cascades
            # reverted to a fixed point. Final (row, col) unique.
            key, move_key = jax.random.split(key)
            new_locs = resolve_movement(move_key, state.agent_locs, all_new_locs)

            # update inventories
            def coin_matcher(p: jnp.ndarray) -> jnp.ndarray:
                return jnp.array([is_apple(state.grid[p[0], p[1]])])

            apple_matches = jax.vmap(coin_matcher)(p=new_locs)
            picked_code = state.grid[new_locs[:, 0], new_locs[:, 1]].astype(jnp.int32)
            picked_hue = jnp.clip(apple_hue(picked_code), 0, self.num_hues - 1)
            picked_stage = jnp.clip(apple_stage(picked_code), 0, NUM_RIPE_STAGES - 1)
            own_value = state.values[jnp.arange(self.num_agents), picked_hue].astype(jnp.float32)
            multiplier = self.PAY_TABLE[order[picked_hue], picked_stage]   # the hidden per-hue pay order over the stages
            apple_value = (own_value * multiplier * apple_matches.reshape(-1)).reshape(-1, 1)
            # the eaten apple's cell is now the agent: reset its age and remember the stage it was eaten at (sets its regrowth speed)
            eaten_cell = jnp.zeros((self.GRID_SIZE_ROW, self.GRID_SIZE_COL), dtype=bool).at[new_locs[:, 0], new_locs[:, 1]].set(True)
            ate_grid = jnp.zeros((self.GRID_SIZE_ROW, self.GRID_SIZE_COL), dtype=bool).at[new_locs[:, 0], new_locs[:, 1]].set(apple_matches.reshape(-1))
            stage_grid = jnp.zeros((self.GRID_SIZE_ROW, self.GRID_SIZE_COL), dtype=jnp.int8).at[new_locs[:, 0], new_locs[:, 1]].set(picked_stage.astype(jnp.int8))
            sp_r, sp_c = self.SPAWNS_APPLE[:, 0], self.SPAWNS_APPLE[:, 1]
            state = state.replace(age=jnp.where(eaten_cell[sp_r, sp_c], 0, state.age),
                                  last_stage=jnp.where(ate_grid[sp_r, sp_c], stage_grid[sp_r, sp_c], state.last_stage))

            
            # rewards = jnp.zeros((self.num_agents, 1))
            # rewards = apple_value

            # single reward or sum reward

            # rewards_sum_all_agents = jnp.zeros((self.num_agents, 1))
            # rewards_sum = jnp.sum(rewards)
            # rewards_sum_all_agents += rewards_sum
            # rewards = rewards_sum_all_agents

            new_invs = state.agent_invs + apple_matches

            state = state.replace(
                agent_invs=new_invs
            )

            # update grid
            old_grid = state.grid

            new_grid = old_grid.at[
                state.agent_locs[:, 0],
                state.agent_locs[:, 1]
            ].set(
                jnp.int16(Items.empty)
            )
            x, y = new_locs[:, 0], new_locs[:, 1]
            new_grid = new_grid.at[x, y].set(self._agents)
            state = state.replace(grid=new_grid)

            # update agent locations
            state = state.replace(agent_locs=new_locs)

            reborn_players, state = _interact(key, state, actions)
            fired = (actions == Actions.zap_forward)
            state = state.replace(
                zap_wait=jnp.where(reborn_players.astype(bool), self.frames_till_respawn,
                                   jnp.maximum(state.zap_wait - 1, 0)).astype(jnp.int16),
                zap_cd=jnp.where(fired, self.zap_cooldown, jnp.maximum(state.zap_cd - 1, 0)).astype(jnp.int16),
            )

            # Occupancy-aware respawn: reborn agents are placed on spawn
            # cells not occupied by any survivor, so no overlap is possible.
            key, respawn_key = jax.random.split(key)
            new_re_locs = resolve_respawn(
                respawn_key, new_locs, reborn_players.astype(bool), self.SPAWNS_PLAYERS
            )
            state = state.replace(reborn_locs=new_re_locs)

            # Rewards are individual only: an apple pays the agent that ate it. There is deliberately no
            # common-reward mode -- summing everyone's apples would remove the social dilemma.
            if self.inequity_aversion:
                rewards = jnp.zeros((self.num_agents, 1))
                original_rewards = apple_value * self.num_agents
                if self.smooth_rewards:
                    should_smooth = (state.inner_t % 1) == 0
                    new_smooth_rewards = 0.99 * 0.01* state.smooth_rewards + original_rewards
                    rewards, disadvantageous, advantageous = self.get_inequity_aversion_rewards_immediate(new_smooth_rewards, state.inner_t, self.inequity_aversion_target_agents, self.inequity_aversion_alpha, self.inequity_aversion_beta)
                    state = state.replace(smooth_rewards=new_smooth_rewards)
                    info = {
                    "original_rewards": original_rewards.squeeze(),
                    "smooth_rewards": state.smooth_rewards.squeeze(),
                    "shaped_rewards": rewards.squeeze(),
                }
                else:
                    rewards, disadvantageous, advantageous = self.get_inequity_aversion_rewards_immediate(original_rewards, state.inner_t, self.inequity_aversion_target_agents, self.inequity_aversion_alpha, self.inequity_aversion_beta)
                    info = {
                    "original_rewards": original_rewards.squeeze(),
                    "shaped_rewards": rewards.squeeze(),
                }
            elif self.svo:
                rewards = jnp.zeros((self.num_agents, 1))
                original_rewards = apple_value * self.num_agents
                rewards, theta = self.get_svo_rewards(original_rewards, self.svo_w, self.svo_ideal_angle_degrees, self.svo_target_agents)
                info = {
                    "original_rewards": original_rewards.squeeze(),
                    "svo_theta": theta.squeeze(),
                    "shaped_rewards": rewards.squeeze(),
                }
            elif self.interest:
                rewards = jnp.zeros((self.num_agents, 1))
                original_rewards = apple_value * self.num_agents

                # Calculate current s_interest based on timestep
                current_s_interest = get_current_s_interest(timestep)
                original_flat = original_rewards.squeeze()

                # Each agent gets s * their_reward + (1-s)/(n-1) * sum_of_others
                total_reward = jnp.sum(original_flat)
                others_reward = total_reward - original_flat  # sum of all other agents' rewards

                rewards = (current_s_interest * original_flat +
                        (1 - current_s_interest) / (self.num_agents - 1) * others_reward).reshape(-1, 1)

                info = {
                    "original_rewards": original_rewards.squeeze(),
                    "shaped_rewards": rewards.squeeze(),
                    "s_interest": current_s_interest,
                }
            else:
                rewards = jnp.zeros((self.num_agents, 1))
                rewards = apple_value * self.num_agents
                info = {"original_rewards": rewards.squeeze(), "shaped_rewards": rewards.squeeze()}
            
            AppleCount = jnp.sum(is_apple(state.grid))
            info["AppleCount_info"] = jnp.zeros((self.num_agents, 1)).squeeze() + AppleCount
            info["trial"] = jnp.zeros((self.num_agents,), dtype=jnp.int32) + state.outer_t
            info["eaten"] = apple_matches.reshape(-1).astype(jnp.int32)
            info["eaten_hue"] = jnp.where(apple_matches.reshape(-1), picked_hue, -1).astype(jnp.int32)
            info["eaten_stage"] = jnp.where(apple_matches.reshape(-1), picked_stage, -1).astype(jnp.int32)
            
            
            state_nxt = State(
                agent_locs=state.agent_locs,
                agent_invs=state.agent_invs,
                inner_t=state.inner_t + 1,
                outer_t=state.outer_t,
                grid=state.grid,
                apples=state.apples,
                freeze=state.freeze,
                reborn_locs=state.reborn_locs,
                age=state.age,
                rule_encoding=state.rule_encoding,
                values=state.values,
                cell_hues=state.cell_hues,
                last_stage=state.last_stage,
                ripen_len=state.ripen_len,
                zap_cd=state.zap_cd,
                zap_wait=state.zap_wait,
            )

            # now calculate if done for inner or outer episode
            inner_t = state_nxt.inner_t
            outer_t = state_nxt.outer_t
            reset_inner = inner_t == num_inner_steps

            # trial boundary: re-lay the orchard, keep the hidden rules and the value table
            state_re = _reset_state(key, state_nxt.rule_encoding, state_nxt.values, state_nxt.cell_hues)

            state_re = state_re.replace(outer_t=outer_t + 1)
            state = jax.tree.map(
                lambda x, y: jnp.where(reset_inner, x, y),
                state_re,
                state_nxt,
            )
            outer_t = state.outer_t
            reset_outer = outer_t == num_outer_steps
            done = {f'{a}': reset_outer for a in self.agents}
            # done = [reset_outer for _ in self.agents]
            done["__all__"] = reset_outer

            obs = _get_obs(state)
            rewards = jnp.where(
                reset_inner,
                jnp.zeros_like(rewards, dtype=jnp.float32),
                rewards
            )


            return (
                obs,
                state,
                rewards.squeeze(),
                done,
                info,
            )

        def _reset_state(
            key: jnp.ndarray, rule_encoding=None, values=None, cell_hues=None
        ) -> State:
            key, subkey, rule_key, value_key = jax.random.split(key, 4)
            hue_key = jax.random.fold_in(value_key, 7)          # separate stream; leaves the existing key split untouched
            if cell_hues is None:
                if self.fixed_patch_hues is not None:
                    slot_hues = self.fixed_patch_hues
                elif self.random_patch_hues and self.patch_hues_with_replacement:
                    slot_hues = jax.random.randint(hue_key, (self.NUM_SLOTS,), 0, self.num_hues)
                elif self.random_patch_hues:
                    slot_hues = jax.random.permutation(hue_key, self.num_hues)[: self.NUM_SLOTS]
                else:
                    slot_hues = jnp.arange(self.NUM_SLOTS, dtype=jnp.int32)
                cell_hues = jnp.asarray(slot_hues, dtype=jnp.int32)[self.APPLE_SLOTS]
            ripen_len0 = jax.random.randint(jax.random.fold_in(key, 13), (len(self.SPAWNS_APPLE),), self.ripen_lo, self.ripen_hi + 1).astype(jnp.int16)
            if rule_encoding is None:
                if self.fixed_rules is not None:
                    from opensocialjax.environments.discovery_rules import encode_harvest_ruleset
                    rule_encoding = encode_harvest_ruleset(self.fixed_rules[0], self.fixed_rules[1])
                elif self.rule_pool is not None:
                    rule_encoding = self.rule_pool.sample(rule_key)
                else:
                    rule_encoding = sample_harvest_ruleset(rule_key, self.num_hues)
            if values is None:
                values = (self.fixed_values if self.fixed_values is not None else
                          jnp.broadcast_to(jax.random.randint(value_key, (1, self.num_hues), 1, self.value_levels + 1), (num_agents, self.num_hues)).astype(jnp.uint8))

            # Find the free spaces in the grid
            grid = jnp.zeros((self.GRID_SIZE_ROW, self.GRID_SIZE_COL), jnp.int16)

            # all_positions = jax.random.permutation(subkey, self.SPAWNS)
            # player_reborn_pos = 
            # total_items = num_agents + NUM_COIN_TYPES * self.NUM_COINS

            # Inside spawns first, then outside spawns; the two pools are
            # disjoint grid cells, so the concatenation has no duplicates
            # (the old code re-drew from a pool that already contained
            # inside_players_pos and could seat two agents on one cell).
            key, subkey2 = jax.random.split(key)
            inside_players_pos = jax.random.permutation(subkey, self.SPAWNS_PLAYER_IN)
            outside_players_pos = jax.random.permutation(subkey2, self.SPAWNS_PLAYERS)
            agent_pos = jnp.concatenate((inside_players_pos, outside_players_pos))[:num_agents]
            wall_pos = self.SPAWNS_WALL

            apple_pos = self.SPAWNS_APPLE

            grid = grid.at[
                apple_pos[:, 0],
                apple_pos[:, 1]
            ].set((APPLE_BASE + cell_hues * NUM_RIPE_STAGES + self.initial_stage).astype(jnp.int16))

            grid = grid.at[
                wall_pos[:, 0],
                wall_pos[:, 1]
            ].set(jnp.int16(Items.wall))


            player_dir = jax.random.randint(
                subkey, shape=(
                    num_agents,
                    ), minval=0, maxval=3, dtype=jnp.int8
            )

            agent_locs = jnp.array(
                [agent_pos[:, 0], agent_pos[:, 1], player_dir],
                dtype=jnp.int16
            ).T

            grid = grid.at[
                agent_locs[:, 0],
                agent_locs[:, 1]
            ].set(jnp.int16(self._agents))

            freeze = jnp.array(
                [[-1]*num_agents]*num_agents,
            dtype=jnp.int16
            )

            return State(
                agent_locs=agent_locs,
                agent_invs=jnp.array([(0,0)]*num_agents, dtype=jnp.int8),
                inner_t=0,
                outer_t=0,
                grid=grid,
                apples=apple_pos,

                freeze=freeze,
                reborn_locs = agent_locs,
                age=(self.initial_stage * ripen_len0).astype(jnp.int16),
                rule_encoding=jnp.asarray(rule_encoding, dtype=jnp.uint8),
                values=jnp.asarray(values, dtype=jnp.uint8),
                cell_hues=jnp.asarray(cell_hues, dtype=jnp.int32),
                last_stage=jnp.zeros((len(self.SPAWNS_APPLE),), dtype=jnp.int8),
                ripen_len=ripen_len0,
                zap_cd=jnp.zeros((num_agents,), dtype=jnp.int16),
                zap_wait=jnp.zeros((num_agents,), dtype=jnp.int16),
            )

        def reset(
            key: jnp.ndarray
        ) -> Tuple[jnp.ndarray, State]:
            state = _reset_state(key)
            obs = _get_obs(state)
            return obs, state
        ################################################################################
        # if you want to test whether it can run on gpu, activate following code
        # overwrite Gymnax as it makes single-agent assumptions
        if jit:
            self.step_env = jax.jit(_step)
            self.reset = jax.jit(reset)
            self.get_obs_point = jax.jit(_get_obs_point)
        else:
            # if you want to see values whilst debugging, don't jit
            self.step_env = _step
            self.reset = reset
            self.get_obs_point = _get_obs_point
        ################################################################################

    @property
    def name(self) -> str:
        """Environment name."""
        return "OpenHarvest"

    @property
    def num_actions(self) -> int:
        """Number of actions possible in environment."""
        return len(Actions)

    def action_space(
        self, agent_id: Union[int, None] = None
    ) -> spaces.Discrete:
        """Action space of the environment."""
        return spaces.Discrete(len(Actions))

    def observation_space(self) -> spaces.Dict:
        """Observation space of the environment."""
        _shape_obs = (
            (self.OBS_SIZE, self.OBS_SIZE, (len(Items)-1) + 10)
            if self.cnn
            else (self.OBS_SIZE**2 * ((len(Items)-1) + 10),)
        )

        return spaces.Box(
                low=0, high=1E9, shape=_shape_obs, dtype=jnp.uint8
            ), _shape_obs
    
    def state_space(self) -> spaces.Dict:
        """State space of the environment."""
        _shape = (
            (self.GRID_SIZE_ROW, self.GRID_SIZE_COL, NUM_TYPES + 4)
            if self.cnn
            else (self.GRID_SIZE_ROW* self.GRID_SIZE_COL * (NUM_TYPES + 4),)
        )
        return spaces.Box(low=0, high=1, shape=_shape, dtype=jnp.uint8)
    
    def render_tile(
        self,
        obj: int,
        agent_dir: Union[int, None] = None,
        agent_hat: bool = False,
        highlight: bool = False,
        tile_size: int = 32,
        subdivs: int = 3,
        beam_orient: Union[str, None] = None,
    ) -> onp.ndarray:
        """
        Render a tile and cache the result
        """

        # Hash map lookup key for the cache
        key: tuple[Any, ...] = (agent_dir, agent_hat, highlight, tile_size, beam_orient)
        if obj:
            key = (obj, 0, 0, 0) + key if obj else key

        if key in self.tile_cache:
            return self.tile_cache[key]

        img = onp.full(
            shape=(tile_size * subdivs, tile_size * subdivs, 3),
            fill_value=SAND_COLOUR,
            dtype=onp.uint8,
        )

        if obj is not None and len(Items) <= obj < len(Items) + self.num_agents:
            # Draw the agent
            agent_color = self.PLAYER_COLOURS[obj-len(Items)]
        elif obj is not None and APPLE_BASE <= obj < APPLE_BASE + NUM_APPLE_CODES:
            paint_apple_tile(img, int(apple_hue(obj)), int(apple_stage(obj)))
        elif obj == Items.wall:
            paint_wall_tile(img)
        elif obj == Items.interact:
            paint_beam_tile(img, (250, 238, 160), (243, 210, 60), beam_orient)
        elif obj == 99:
            fill_coords(img, point_in_rect(0, 1, 0, 1), (44.0, 160.0, 44.0))
        elif obj == 100:
            fill_coords(img, point_in_rect(0, 1, 0, 1), (214.0, 39.0, 40.0))
        elif obj == 101:
            # white square
            fill_coords(img, point_in_rect(0, 1, 0, 1), (255.0, 255.0, 255.0))

        # Overlay the agent on top
        if agent_dir is not None:
            draw_agent(img, agent_dir, agent_color)

        # Highlight the cell if needed (soft, so the obs windows don't wash
        # out the scene like the old 30% white blend did)
        if highlight:
            highlight_img(img, alpha=0.12)

        # Downsample the image to perform supersampling/anti-aliasing
        img = downsample(img, subdivs)

        # Cache the rendered tile
        self.tile_cache[key] = img
        return img

    def render(
        self,
        state: State,
    ) -> onp.ndarray:
        """
        Render this grid at a given scale
        :param r: target renderer object
        :param tile_size: tile size in pixels
        """
        tile_size = 32
        highlight_mask = onp.zeros(onp.asarray(self.GRID).shape, dtype=bool)

        # Compute the total grid size
        width_px = self.GRID.shape[1] * tile_size
        height_px = self.GRID.shape[0] * tile_size

        img = onp.zeros(shape=(height_px, width_px, 3), dtype=onp.uint8)

        # Pull device state to host ONCE; the per-cell loop below must stay
        # pure numpy/python (any jax comparison would be a blocking sync).
        grid = onp.asarray(state.grid)
        grid = onp.pad(
            grid, ((self.PADDING, self.PADDING), (self.PADDING, self.PADDING)),
            constant_values=int(Items.wall)
        )
        agent_locs = onp.asarray(state.agent_locs)

        for a in range(self.num_agents):
            startx, starty = self.get_obs_point(state.agent_locs[a])
            startx, starty = int(startx), int(starty)
            highlight_mask[
                startx : startx + self.OBS_SIZE, starty : starty + self.OBS_SIZE
            ] = True

        # grid code -> facing direction, one entry per agent stamp
        first_agent_code = len(Items)
        agent_dirs = {
            first_agent_code + a: int(agent_locs[a, 2])
            for a in range(self.num_agents)
        }

        # Render the grid
        beam_codes = (int(Items.interact),)
        for j in range(0, grid.shape[1]):
            for i in range(0, grid.shape[0]):
                cell = int(grid[i, j])
                beam_orient = None
                if cell in beam_codes:
                    h = ((j > 0 and grid[i, j - 1] == cell)
                         or (j + 1 < grid.shape[1] and grid[i, j + 1] == cell))
                    v = ((i > 0 and grid[i - 1, j] == cell)
                         or (i + 1 < grid.shape[0] and grid[i + 1, j] == cell))
                    if h and not v:
                        beam_orient = "h"
                    elif v and not h:
                        beam_orient = "v"
                tile_img = self.render_tile(
                    cell if cell != 0 else None,
                    agent_dir=agent_dirs.get(cell),
                    agent_hat=False,
                    highlight=bool(highlight_mask[i, j]),
                    tile_size=tile_size,
                    beam_orient=beam_orient,
                )

                ymin = i * tile_size
                ymax = (i + 1) * tile_size
                xmin = j * tile_size
                xmax = (j + 1) * tile_size
                img[ymin:ymax, xmin:xmax, :] = tile_img
        # Crop the padding; the image is NOT rotated any more, so it has the
        # same orientation as the map_ASCII the env was built from.
        img = img[
            (self.PADDING - 1) * tile_size : -(self.PADDING - 1) * tile_size,
            (self.PADDING - 1) * tile_size : -(self.PADDING - 1) * tile_size,
            :,
        ]
        return img

    def render_inventory(self, inventory, width_px) -> onp.array:
        tile_height = 32
        height_px = NUM_COIN_TYPES * tile_height
        img = onp.zeros(shape=(height_px, width_px, 3), dtype=onp.uint8)
        tile_width = width_px // self.NUM_COINS
        for j in range(0, NUM_COIN_TYPES):
            num_coins = inventory[j]
            for i in range(int(num_coins)):
                cell = None
                if j == 0:
                    cell = 99
                elif j == 1:
                    cell = 100
                tile_img = self.render_tile(cell, tile_size=tile_height)
                ymin = j * tile_height
                ymax = (j + 1) * tile_height
                xmin = i * tile_width
                xmax = (i + 1) * tile_width
                img[ymin:ymax, xmin:xmax, :] = onp.resize(
                    tile_img, (tile_height, tile_width, 3)
                )
        return img

    def render_time(self, state, width_px) -> onp.array:
        inner_t = state.inner_t
        outer_t = state.outer_t
        tile_height = 32
        img = onp.zeros(shape=(2 * tile_height, width_px, 3), dtype=onp.uint8)
        tile_width = width_px // (self.num_inner_steps)
        j = 0
        for i in range(0, inner_t):
            ymin = j * tile_height
            ymax = (j + 1) * tile_height
            xmin = i * tile_width
            xmax = (i + 1) * tile_width
            img[ymin:ymax, xmin:xmax, :] = onp.int8(255)
        tile_width = width_px // (self.num_outer_steps)
        j = 1
        for i in range(0, outer_t):
            ymin = j * tile_height
            ymax = (j + 1) * tile_height
            xmin = i * tile_width
            xmax = (i + 1) * tile_width
            img[ymin:ymax, xmin:xmax, :] = onp.int8(255)
        return img
    
    def get_inequity_aversion_rewards_immediate(self, array, inner_t, target_agents=None, alpha=5, beta=0.05):
        """
        Calculate inequity aversion rewards using immediate rewards, based on equation (3) in the paper
        
        Args:
            array: shape: [num_agents, 1] immediate rewards r_i^t for each agent
            target_agents: list of agent indices to apply inequity aversion
            alpha: inequity aversion coefficient (when other agents' rewards are greater than self)
            beta: inequity aversion coefficient (when self's rewards are greater than others)
        Returns:
            subjective_rewards: adjusted subjective rewards u_i^t after inequity aversion
        """
        # Ensure correct input shape
        assert array.shape == (self.num_agents, 1), f"Expected shape ({self.num_agents}, 1), got {array.shape}"
        
        # Calculate inequality using immediate rewards
        r_i = array  # [num_agents, 1]
        r_j = jnp.transpose(array)  # [1, num_agents]
        
        # Calculate inequality
        disadvantageous = jnp.maximum(r_j - r_i, 0)  # when other agents' rewards are higher
        advantageous = jnp.maximum(r_i - r_j, 0)     # when self's rewards are higher
        
        # Create mask to exclude self-comparison
        mask = 1 - jnp.eye(self.num_agents)
        disadvantageous = disadvantageous * mask
        advantageous = advantageous * mask
        
        # Calculate inequality penalty
        n_others = self.num_agents - 1
        inequity_penalty = (alpha * jnp.sum(disadvantageous, axis=1, keepdims=True) +
                           beta * jnp.sum(advantageous, axis=1, keepdims=True)) / n_others

        # Calculate subjective rewards u_i^t = r_i^t - inequality penalty
        subjective_rewards = array - inequity_penalty

        subjective_rewards = jnp.where(jnp.all(array == 0), -(alpha + beta) * n_others, subjective_rewards)
        
        # Apply inequity aversion only to target agents if specified
        if target_agents is not None:
            target_agents_array = jnp.array(target_agents)
            agent_mask = jnp.zeros(self.num_agents, dtype=bool)
            agent_mask = agent_mask.at[target_agents_array].set(True)
            agent_mask = agent_mask.reshape(-1, 1)  # [num_agents, 1]
            return jnp.where(agent_mask, subjective_rewards, array),jnp.sum(disadvantageous, axis=1, keepdims=True),jnp.sum(advantageous, axis=1, keepdims=True)
        else:
            return subjective_rewards,jnp.sum(disadvantageous, axis=1, keepdims=True),jnp.sum(advantageous, axis=1, keepdims=True)

    def get_svo_rewards(self, array, w=0.5, ideal_angle_degrees=45, target_agents=None):
        """
        Reward shaping function based on Social Value Orientation (SVO)
        
        Args:
            array: shape: [num_agents, 1] immediate rewards r_i for each agent
            w: SVO weight to balance self-reward and social value (0 <= w <= 1)
               w=0 means completely selfish, w=1 means completely altruistic
            ideal_angle_degrees: ideal angle in degrees
               - 45 degrees means complete equality
               - 0 degrees means completely selfish
               - 90 degrees means completely altruistic
            target_agents: list of agent indices to apply SVO
        
        Returns:
            shaped_rewards: rewards adjusted by SVO
            theta: reward angle in radians
        """
        # Ensure correct input shape
        assert array.shape == (self.num_agents, 1), f"Expected shape ({self.num_agents}, 1), got {array.shape}"
        
        # Convert ideal angle from degrees to radians
        ideal_angle = (ideal_angle_degrees * jnp.pi) / 180.0
        
        # Calculate group average reward r_j (excluding self)
        mask = 1 - jnp.eye(self.num_agents)  # [num_agents, num_agents]
        # Modified: use matrix multiplication to calculate other agents' rewards
        others_rewards = jnp.matmul(mask, array)  # [num_agents, 1]
        mean_others = others_rewards / (self.num_agents - 1)  # divide by number of other agents
        
        # Calculate reward angle θ(R) = arctan(r_j / r_i)
        r_i = array  # [num_agents, 1]
        r_j = mean_others  # [num_agents, 1]
        theta = jnp.arctan2(r_j, r_i)
        
        # Calculate social value oriented utility
        # U(r_i, r_j) = r_i - w * |θ(R) - ideal_angle|
        angle_deviation = jnp.abs(theta - ideal_angle)
        svo_utility = r_i - self.num_agents * w * angle_deviation

        # Apply SVO only to target agents if specified
        if target_agents is not None:
            target_agents_array = jnp.array(target_agents)
            agent_mask = jnp.zeros(self.num_agents, dtype=bool)
            agent_mask = agent_mask.at[target_agents_array].set(True)
            agent_mask = agent_mask.reshape(-1, 1)  # [num_agents, 1]
            return jnp.where(agent_mask, svo_utility, array), theta
        else:
            return svo_utility, theta

    def get_standardized_svo_rewards(self, array, w=0.5, ideal_angle_degrees=45, target_agents=None):
        """
        Reward shaping function based on Social Value Orientation (SVO)
        """
        # Ensure correct input shape
        assert array.shape == (self.num_agents, 1), f"Expected shape ({self.num_agents}, 1), got {array.shape}"
        
        # Convert ideal angle from degrees to radians
        ideal_angle = (ideal_angle_degrees * jnp.pi) / 180.0
        
        # Calculate group average reward r_j (excluding self)
        mask = 1 - jnp.eye(self.num_agents)
        others_rewards = jnp.matmul(mask, array)
        mean_others = others_rewards / (self.num_agents - 1)
        
        # Calculate reward angle θ(R) = arctan(r_j / r_i)
        r_i = array
        r_j = mean_others
        theta = jnp.arctan2(r_j, r_i)
        
        # Convert angle to [0, 2π] range
        theta = (theta + 2 * jnp.pi) % (2 * jnp.pi)
        
        # Calculate angle deviation and normalize to [0, 1] range
        angle_deviation = jnp.abs(theta - ideal_angle)
        angle_deviation = jnp.minimum(angle_deviation, 2 * jnp.pi - angle_deviation)  # take minimum deviation
        normalized_deviation = angle_deviation / jnp.pi  # normalize to [0, 1]
        
        # Use multiplicative form of penalty instead of subtraction
        svo_utility = r_i * (1 - w * normalized_deviation)
        
        # Apply SVO only to target agents if specified
        if target_agents is not None:
            target_agents_array = jnp.array(target_agents)
            agent_mask = jnp.zeros(self.num_agents, dtype=bool)
            agent_mask = agent_mask.at[target_agents_array].set(True)
            agent_mask = agent_mask.reshape(-1, 1)
            return jnp.where(agent_mask, svo_utility, array), theta
        else:
            return svo_utility, theta